# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-20 08:55
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20191119_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
